# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(
        task: "assemble",
        build_type: "Release"
    )
    upload_to_play_store(
	track: "beta",
        package_name: "com.gyeong.architecturekotlin",
        release_status: "completed",
        skip_upload_apk: true
    )
      
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Build debug and test APK for screenshots"
  lane :build_for_screengrab do
    gradle(
      task: 'clean'
    )
    gradle(
      task: 'assemble',
      build_type: 'Debug'
    )
    gradle(
      task: 'assemble',
      build_type: 'AndroidTest'
    )
  screengrab
  end

  desc "Increment version code"
  lane :increment_vc do
    increment_version_code(
	gradle_file_path: "./app/build.gradle"
    )  
  end

  desc "Upload alpha test"
  lane :release_alpha do
        increment_vc
    gradle(
	task: "bundle"
    )
    supply(
	track: "alpha",
	aab: ENV["APP_BUNDLE_PATH"],
	release_status: "draft"
    )
  end

  desc "Upload beta test"
  lane :release_beta do
  	increment_vc
    gradle(
	task: "bundle"
    )  
    upload_to_play_store(
	track: "beta",
	aab: ENV["APP_BUNDLE_PATH"],
	release_status: "draft"
    )
  end  
  
  desc "Upload to internal app sharing"
  lane :release_app_sharing do
    upload_to_play_store_internal_app_sharing(
   	aab: ENV["APP_BUNDLE_PATH"]	
    )
  end 
 
  desc "Deploy a new version to the Google Play"
  lane :deploy do
	# The lane you created previously to increment app's 'version code'
   	increment_vc
	# The build release app bundle lane created previously
	# build_bundle
	# Uploads Android App Bundle to Play Console
    gradle(
 	task: "bundle"
    )
    upload_to_play_store(
 	skip_upload_apk: true,
	skip_upload_screenshots: true,
	package_name: "com.gyeong.architecturekotlin",
	release_status: "draft"
    )
  end

  desc "Disxfftribution test"
  lane :distribution do
    gradle(task: "clean assembleRelease")
    firebase_app_distribution(
        app: ENV["FIREBASE_APP_ID"],
        firebase_cli_token: ENV["FIREBASE_APP_TOKEN"],
        debug: true)
    end
end
